#!/usr/bin/env bash
set -euo pipefail

# Provisions a Neon project for TeamPulse and writes connection strings to .env.production.local
#
# Usage:
#   1. Create API key: https://console.neon.tech/app/settings/api-keys
#   2. export NEON_API_KEY="napi_..."
#   3. npm run db:neon
#
# Or interactive login (opens browser):
#   npm run db:neon

PROJECT_NAME="${NEON_PROJECT_NAME:-teampulse}"
REGION="${NEON_REGION:-aws-eu-central-1}"
ENV_FILE="${1:-.env.production.local}"

echo "→ Creating Neon project «${PROJECT_NAME}» in ${REGION}..."

PROJECT_ID=$(npx neonctl projects create \
  --name "$PROJECT_NAME" \
  --region-id "$REGION" \
  -o json | node -e "
    const d = JSON.parse(require('fs').readFileSync(0, 'utf8'));
    const id = d.project?.id ?? d.id;
    if (!id) throw new Error('Could not read project id from neonctl output');
    console.log(id);
  ")

echo "→ Project ID: ${PROJECT_ID}"

echo "→ Fetching pooled connection string..."
POOLED=$(npx neonctl connection-string \
  --project-id "$PROJECT_ID" \
  --pooled \
  -o json | node -e "
    const raw = require('fs').readFileSync(0, 'utf8').trim();
    const d = JSON.parse(raw);
    const url = typeof d === 'string' ? d : d.connection_uri ?? d.connection_string;
    if (!url) throw new Error('Could not read connection string');
    console.log(url);
  ")

DIRECT="${POOLED//-pooler/}"
SEPARATOR=$([[ "$POOLED" == *"?"* ]] && echo "&" || echo "?")

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-neon.sh — add these to Vercel Environment Variables
DATABASE_URL="${POOLED}${SEPARATOR}sslmode=require"
DIRECT_URL="${DIRECT}${SEPARATOR}sslmode=require"
AUTH_SECRET="$(openssl rand -base64 32)"
NEXTAUTH_URL="https://YOUR-APP.vercel.app"
UPSTASH_REDIS_REST_URL=""
UPSTASH_REDIS_REST_TOKEN=""
EOF

echo ""
echo "✓ Saved to ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. npm run db:deploy          # applies schema to Neon"
echo "  2. Copy vars from ${ENV_FILE} → Vercel → Environment Variables"
echo "  3. Set NEXTAUTH_URL to your Vercel domain"
echo "  4. vercel --prod"
